### ISSUE TITLE
startGUIRefresh in CaDSRobotGUISwing not working

### ISSUE THREAD

**Issue by nos-home** [Transport-Protocol/CaDSPracticalExamVS#17]
when executing startGUIRefresh it throws the following exception:

```
Exception in thread "main" java.lang.ClassCastException: cads.gnarls.Controller cannot be cast to org.cads.ev3.rmi.consumer.CaDSRMIConsumer
	at org.cads.ev3.gui.swing.CaDSRobotGUIRefresh.<init>(Unknown Source)
	at org.cads.ev3.gui.swing.CaDSRobotGUISwing.startGUIRefresh(Unknown Source)
```

the Cast probably should be to the interface ICaDSRMIConsumer instead of CaDSRMIConsumer.

**Comment by HaukeBu** [comment]
Hi!
Which Java Version do you use? 
Which Interface are you implementing with your Controller?

**Comment by nos-home** [comment]
* eclipse says: JavaSE-1.7 (*.jar coming from jdk1.8.0_144)
* i'm on osx


```java
public class Controller implements
ICaDSEV3RobotFeedBackListener, 
ICaDSEV3RobotStatusListener, 
ICaDSRMIConsumer,
IIDLCaDSEV3RMIMoveGripper, 
IIDLCaDSEV3RMIMoveHorizontal, 
IIDLCaDSEV3RMIMoveVertical, 
IIDLCaDSEV3RMIUltraSonic, 
Runnable {
	CaDSRobotGUISwing view;

	public Controller() {
		super();
		this.view = new CaDSRobotGUISwing(this, this, this, this, this);
		view.startGUIRefresh(1000);
	}
 /* ... all stubs here */
}
```

**Comment by HaukeBu** [comment]
Issue is fixed.
